#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  shoot,          sensorTouch)
#pragma config(Sensor, dgtl2,  lift,           sensorTouch)
#pragma config(Motor,  port1,           LL3,           tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LL1,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LR2,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LL2,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           BR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LR3,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LR1,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

task main()
{
while (true) {
			// Y component, X component, Rotation
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		// Motor values can only be updated every 20ms
		wait10Msec(2);

			if (vexRT[Btn6U]) {
			motor[LL1] = 127;
			motor[LL2] = 127;
			motor[LR1] = 127;
			motor[LR2] = 127;
			motor[LL3] = 127;
			motor[LR3] = 127;
		}
		else if (vexRT[Btn5U]) {
			motor[LL1] = -127;
			motor[LL2] = -127;
			motor[LR1] = -127;
			motor[LR2] = -127;
			motor[LL3] = -127;
			motor[LR3] = -127;
		}
		else if (vexRT[Btn6D]) {
			motor[LL1] = 0;
			motor[LL2] = 0;
			motor[LR1] = 0;
			motor[LR2] = 0;
			motor[LL3] = 0;
			motor[LR3] = 0;
		}
	}

}
